### ISSUE TITLE
Non-determinism in PAR output

### ISSUE THREAD

**Issue by mattmoor** [google/subpar#41]
See: https://github.com/bazelbuild/rules_python/pull/10#issuecomment-330853158

**Comment by duggelz** [comment]
Note to self, we'll set all timestamps to `Jan 1 1980 00:00:00`, to match internal tools, and because it's the earliest timestamp supported by the zip format.  Note that FAT filesystems round all timestamps to a 2 second granularity, so picking something like 1 second after midnight is not a good choice.

Also relevant: https://www.python.org/dev/peps/pep-0552/

**Comment by duggelz** [comment]
Fixed.

**Comment by duggelz** [comment]
Oops, this isn't merged yet.

**Comment by gpshead** [comment]
Note for the future: Python >=3.7 can use non-timestamp based .pyc files. https://www.python.org/dev/peps/pep-0552/
